image: fedora/31
packages:
  - golang-bin
sources:
  - https://git.sr.ht/~fnux/yggdrasil-go-coap
environment:
  GOPATH: /tmp/go
  GOBIN: /tmp/go/bin
tasks:
  - fetch: |
      cd yggdrasil-go-coap
      go get -v
  - build: |
      cd yggdrasil-go-coap
      go build
